url: "https://davidhiskett.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/awalsh" # the subpath of your site, e.g. /blog
title: "Annabel Walsh" # the name of your site, e.g. ACME Corp.